/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ice_jni_dde_JNIDDE */

#ifndef _Included_com_ice_jni_dde_JNIDDE
#define _Included_com_ice_jni_dde_JNIDDE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ice_jni_dde_JNIDDE
 * Method:    ddeExecute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ice_jni_dde_JNIDDE_ddeExecute
  (JNIEnv *, jclass, jstring, jstring, jstring, jboolean);

/*
 * Class:     com_ice_jni_dde_JNIDDE
 * Method:    shellExecute
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ice_jni_dde_JNIDDE_shellExecute
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
